### ISSUE TITLE
Real time data as input

### ISSUE THREAD

**Issue by dataliven** [artzub/blackhole.js#24]
It's a cute library and I want to feed in data in real time, please advise how to do, thanks.

**Comment by shernshiou** [comment]
@artzub any example how to use it for realtime?

**Comment by artzub** [comment]
@shernshiou ok, later! I'll made an example on codepen.io

**Comment by shernshiou** [comment]
thanks @artzub

**Comment by artzub** [comment]
Sorry that so long time not answer =) 
The fast example.
```javascript
...
bh.settings.realtime = true;
...
bh.start(somedata);
...
// and after getting new data need use
bh.append(newdata);
```

**Comment by tropicalpb** [comment]
Does this support a moving window-like FIFO behavior with real time inputs?  For example, if the window is 10 polls, then for every poll beyond 10th, the earliest poll's data would be removed from canvas.  It would be great if there's an example on how to use this.  Thanks
